### ISSUE TITLE
test(tdm-ieee): the unexpected-shape fixture is a JSON guess; IEEE actually answers text/xml, and the 403 never reaches the JSON path at all

### ISSUE THREAD

**Issue by sotashimozono** [sotashimozono/doiget#460]
ADR-0042 shipped `tdm-ieee` against an inferred contract and said the first contact with the real
endpoint should correct it. One unauthenticated request is enough to correct part of it now.

## Observed

```
$ curl -A 'doiget/0.8.9 (+https://github.com/QAtlasHub/doiget)' \
    'https://ieeexploreapi.ieee.org/api/v1/search/articles?doi=10.1109%2FTSP.2018.2812747&format=json'

HTTP=403  content-type=text/xml
<h1>Developer Inactive</h1>
```

**Confirmed:** the base and path are right — the host resolves and the endpoint is served.

**Wrong in the fixture:** the failure body is **not JSON**, and `format=json` does not change that.
`tdm_ieee.rs` has

```rust
const SAMPLE_UNEXPECTED_SHAPE: &str = r#"{"error": "Developer Inactive"}"#;
```

which is a JSON guess at a response that is `text/xml`. The test built on it
(`an_unexpected_envelope_names_the_field_and_quotes_the_body`) asserts against a shape the server
never sends.

## The more important consequence

A 403 is an `HttpError::HttpStatus`, so it never reaches the JSON parsing this module does — the
`SourceSchema` branch the test exercises is not the branch a key-less or inactive-key user hits.
Nothing currently covers what they *do* hit, and that is the single most likely first-contact
outcome: a key pending activation reads exactly like no key at all.

Two things worth asserting on that path and currently unasserted:

1. **The message is comprehensible.** `Developer Inactive` means "your key is not activated yet",
   which is a different action from "your key is wrong". If the surfaced text is a bare
   `HTTP 403 from <url>`, the user cannot tell.
2. **The key is redacted.** IEEE is a query-parameter-auth source, so the URL in
   `HttpError::HttpStatus` — which is `tracing`-logged — carries `apikey=`. #457 taught
   `redact_api_key_query` the `apikey` spelling; nothing tests it end-to-end through the HTTP
   layer, only the module-local redactor in isolation.

## Fix

- Replace `SAMPLE_UNEXPECTED_SHAPE` with the observed `text/xml` body.
- Add a wiremock test replaying `403 + text/xml + <h1>Developer Inactive</h1>` and assert the
  surfaced error names the condition and does **not** contain the key.
- Record the observed facts in ADR-0042 and the module docs, and narrow the `(unverified)` marking
  in `SOURCES.md` §1 to what is still unverified: the 200-response envelope and the rate limits.

Refs #430, #457, #146, ADR-0042.

**Comment by sotashimozono** [comment]
Fixing this turned up a second, larger defect in the same module, so the branch carries both.

## `tdm-ieee` did not compile on its own

```
$ cargo build -p doiget-core --no-default-features --features oa-only,tdm-ieee
error[E0609]: no field `api_key` on type `&TdmGrant`
error[E0560]: struct `TdmGrant` has no field named `api_key`
```

`TdmGrant::api_key` and the three sites that populate it are gated on

```rust
#[cfg(any(feature = "tdm-elsevier", feature = "tdm-aps", feature = "tdm-springer"))]
```

— the first three publishers and not the fourth. #457 updated `docs/CAPABILITY.md`'s
rendering of that `cfg` and missed the code.

CI could not see it: the only Tier-3 jobs are the four-way union, where the other three
features are always present and the field always exists, and an `oa-only,tdm-aps`
singleton. There is no `oa-only,tdm-ieee`.

That singleton exists for exactly this reason — its comment says *"the singleton proves
`tdm-*` does not secretly depend on `metadata`"* — so the lesson is that **one** singleton
is not enough. Each publisher needs its own, and the matrix now has `oa-only,tdm-ieee`
alongside `oa-only,tdm-aps`.

## Also on the branch

- The stale `http.rs` comment claiming *"No other source puts a secret in the query
  string"* — no longer true since #430, and it sits directly above the redaction that
  now handles both spellings.
